name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR package
        run: mvn clean package -DskipTests

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          source: "target/*.jar"
          target: "/home/${{ secrets.AWS_USER }}/app/"  # target 디렉터리 아님, app 바로 밑에 저장

      - name: SSH and restart app safely
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            set -euxo pipefail
            APP_DIR="/home/${{ secrets.AWS_USER }}/app"

            echo "===== Starting new app ====="
            JAR_FILE=$(ls -t "$APP_DIR"/target/*.jar | head -n 1)
            if [ -z "$JAR_FILE" ]; then
              echo "ERROR: No JAR file found in $APP_DIR"
              exit 1
            fi

            nohup setsid java -jar "$JAR_FILE" > "$APP_DIR/app.log" 2>&1 & disown

            sleep 5
            echo "===== Running java processes ====="
            ps -ef | grep java || true

            echo "===== Tail app.log ====="
            tail -n 20 "$APP_DIR/app.log" || true
